"""init

Revision ID: 259dc8d3d432
Revises: 
Create Date: 2024-10-16 15:38:07.291067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259dc8d3d432'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), server_default='', nullable=False, comment='news title'),
    sa.Column('content', sa.String(), server_default='', nullable=True, comment='news content'),
    sa.Column('source', sa.Enum('BLOOMBERG', 'BARRONS', 'UNKNOWN', name='sourcetype', native_enum=False), server_default='UNKNOWN', nullable=False, comment='news source'),
    sa.Column('article_url', sa.String(), server_default='', nullable=False, comment='news url'),
    sa.Column('image_url', sa.String(), server_default='', nullable=True, comment='news image url'),
    sa.Column('day', sa.String(length=50), server_default='', nullable=False, comment='day of news'),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='news published time'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
