import type {Metadata} from "next";
import localFont from "next/font/local";
import "@/public/globals.css";
import {cn} from "@/lib/utils";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>

      <body
          className={cn(
              "bg-background font-sans antialiased",
              geistSans.variable,
              geistMono.variable
          )}
      >
        <main>
          {children}
        </main>
      </body>
      </html>
  );
}
